spring:
  application:
    name: config
  rabbitmq:
    host: 120.79.193.21
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: git@github.com:dudj/config-repo.git
          username: 13020078873@163.com
          password: LKK521liukeke
          basedir: D:\ddj\springcloud\config\basedir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
#将config的接口暴露出去
management:
  endpoints:
    web:
      expose: "*"
#      exposure:
#        include: "*"
