
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://120.79.193.21:8080/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
  instance:
    prefer-ip-address: true
spring:
  application:
    name: eureka
server:
#    servlet:
#        context-path: /eureka
  port: 8761

